--- 
title: "Introduction to Quantitative Techniques in R for Conservation Biology"
author: "Dr. Yolanda Wiersma"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/ConsBiolQuantFun
description: "This is a manual for the Quantitative Techniques Module in BIOL 4651/7944 (Conservation in Practice)"
---

# Introduction

Biology, including ecology and conservation, is becoming increasingly quantitative. Familiarity with a range of statistical tools (frequentist, multivariate, Bayesian) is expected. Many researchers draw on quantitative methods; whether it is process or mathematical modelling, programming, bioinformatics, or bioeconomic analyses. We will only touch on key concepts in quantitative methods; in-depth training would require multiple full-semester courses. 

In the process of increasing quantitative skills across the Biology curriculum, we have prepared an online guide for using R, that is designed for new users, and as a reference document for all Biology students. You can access it [here](https://ahurford.github.io/quant-guide-all-courses/). 
In this three-week module, we will carry out a few exercise that mimics some of the quantitative skills that you need to be a successful conservation biologist. These include:

1. Data management (with an introduction to the ```dplyr``` package)
1. Plotting data effectively (with an introduction to the ```ggplot2``` package)
1. Univariate and multivariate statistical analysis (with an introduction to the ```vegan``` package)





```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
